spring.application.name=exam
# Oracle
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=gestion_notes
spring.data.mongodb.username=taoufik
spring.data.mongodb.password=oraclemongo123
spring.data.mongodb.authentication-database=gestion_notes
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=system
spring.datasource.password=oracle
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
